### ISSUE TITLE
v1.0.4 is vulnerable to CVE-2018-8292

### ISSUE THREAD

**Issue by janusw** [MatejFranceskin/GeoidHeightsDotNet#14]
I recently stumbled across a security warning in a private Gitlab instance that points toward a security vulnerability that seems to be introduced via a dependency on GeoidHeightsDotNet 1.0.4:

* "Exposure of Sensitive Information to an Unauthorized Actor"
* [CVE-2018-8292](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-8292) 
* https://github.com/advisories/GHSA-7jgj-8wvc-jh57
* https://github.com/dotnet/announcements/issues/88
* https://nvd.nist.gov/vuln/detail/CVE-2018-8292

The affected package is [System.Net.Http:4.3.0](https://www.nuget.org/packages/System.Net.Http/4.3.0) and the dependency chain is:

* GeoidHeightsDotNet:1.0.4
* NETStandard.Library:1.6.1
* System.Net.Http:4.3.0

**Comment by janusw** [comment]
I think the simplest way of fixing this kind of problem is to add more modern target frameworks to the library. Currently it only targets .NET Standard 1.1, but via multi-targeting one can simply add further ones, even without removing support for .NET Standard 1.1 yet.

For the case here, adding a .NET Standard 2.0 is probably enough, but while we're at it, adding .NET 6 (or 7 or 8) might be a good idea as well.

**Comment by jasells** [comment]
These are false-positives from naive scanners.  The scan is simply picking up the fact that .Net Stnd1.6 _as a whole_ includes System.Net.Http:4.3.0 as a standard reference _minimum_.  This library _does not_ have System.Net.Http:4.3.0, or any version of it, as a dependency.

The _only_ possible way the issue can manifest is in an app consuming GeoHieghtsDotNet _AND_ also has _application_ code that uses System.Net.Http package, _but also_ includes the 4.3.0 version of the package _explicitly_, which is of no concern or responsibility to this library one way or the other.  Any .Net 6 or newer (probably even .Net Core 5) app already has newer package refs that will replace System.Net.Http:4.3.0 with a newer version unless overriden by explicit application package requirements.   

Changing to .Net Stndard 2.0, 2.1 or .Net6 won't affect it in any way, since the consuming app can still define the System.Net.Http version it uses.

**Comment by jasells** [comment]
you can read more here https://dotnet.microsoft.com/en-us/platform/dotnet-standard

If you're familiar with IoC or dependency injection, .Net Standard is a similar mechanism, so these scanners are picking up on the API _contracts_ defined in the older 1.6 definition, but are updated by the _actual_ runtime when the app runs.

**Comment by janusw** [comment]
> These are false-positives from naive scanners. The scan is simply picking up the fact that .Net Stnd1.6 _as a whole_ includes System.Net.Http:4.3.0 as a standard reference _minimum_. This library _does not_ have System.Net.Http:4.3.0, or any version of it, as a dependency.

Well, yes, it's most probably a false positive. Indeed GeoidHeights does not use `System.Net.Http` at all, but the dependency only comes in through the `NETStandard.Library` package.

The problem basically seems to be due to the explicit reference to System.Net.Http:4.3.0 in NETStandard.Library:1.6.1. That reference seems to be gone completely in .NET Standard 2.0, so indeed adding a netstandard2.0 (or later) target should hopefully get rid of the false positives.

**Comment by jasells** [comment]
It is _definitely not_  adependency, because `NETStandard.Library` package contains _no_ implementation, only API's.  Implementation _only_ exists in Core or Framework runtimes.  The version of NetStandard used by this or any library only _declares_ the version of the _API's_ expected by _this_ package _if_ called so that this package's lib can be _linked_ to the _actual_ library provided by the consuming app's 'TargetFramework' at build time.  

Upgrading to .NetStandard 2.0 _increases_ the available API's, and by that logic, _increases_ the "potential vulnerabilities" since it now has "more dependencies".  

As I said, the scanner that flagged this doesn't understand how .Net works, and is confusing API versions with implementation versions, or likely doesn't even know there is a difference since it is probably a generic scanner for multiple languages.

**Comment by jasells** [comment]
To put it more simply, the whole point of the design of NetStandard is that a lib like this _does not_ need to be actively maintained to address these kinds of issues.  The only reason to update this lib is if there are code changes to it directly.

This issue is addressed by the stack using this lib, and _can only be addressed by that stack_.

**Comment by janusw** [comment]
> To put it more simply, the whole point of the design of NetStandard is that a lib like this _does not_ need to be actively maintained to address these kinds of issues.

Well, yes, true in principle.

But let me give you my take on this: In my view .NET Standard is sort of an early mechanism for having some sort of cross-platform support for .NET, and it was never the best solution for that. By now it is mostly superseded by modern .NET (Core) versions (v6 and upward), which solve this problem much more elegantly and provided a more tightly-integrated cross-platform support. Therefore .NET Standard is not very relevant any more IMHO.

Also, I don't think there is _anything_ wrong with updating this library by providing additional target frameworks. In v1.0.5 I'm explicitly keeping the old netstandard1.1 target and add netstandard2.0 and net6.0 to it.

**Comment by janusw** [comment]
> Upgrading to .NetStandard 2.0 _increases_ the available API's

True, but what I meant is that, on a package level, 2.0 reduces the number of explicit dependencies, see:

https://www.nuget.org/packages/NETStandard.Library#dependencies-body-tab

As you can see, .NETStandard up to 1.6 depends on all kinds of System.* libs, while .NETStandard 2.0 only depends on Microsoft.NETCore.Platforms. I don't really understand the reasons for that change, though. Of course all the System.* libs are still usable in 2.0, so probably just the way they are referenced has changed (so that NETStadard.Library does not pull in all these references any more, if they are not actually used).


> and by that logic, _increases_ the "potential vulnerabilities" since it now has "more dependencies".

That statement is highly questionable in several ways, but I won't go into such general discussions right now.


> As I said, the scanner that flagged this doesn't understand how .Net works, and is confusing API versions with implementation versions, or likely doesn't even know there is a difference since it is probably a generic scanner for multiple languages.

At least it explicitly supports .NET/C#/NuGet, and it takes `packages.lock.json` files as input, which are generated by `dotnet restore`. Therefore I don't really think that only the Gitlab tooling is to blame for the false positives here.

`packages.lock.json` itself lists the ancient `System.Net.Http:4.3.0` when depending on `GeoidHeightsDotNet:1.0.4`, even if the application targets net8.0, which should use much newer system libs. So it seems to me like the whole .NET dependency system is a bit weird and quirky (or maybe I just don't understand it well enough?).

**Comment by janusw** [comment]
In any case, the false positives in this issue are removed for me by upgrading to GeoidHeightsDotNet v1.0.5 (in a net8.0 application).

It doesn't seem to me like the false positives are caused by the Gitlab dependency scanner itself, but rather by the way that NETStandard.Library references the System libs in netstandard1.1.
